<Project>
    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="xunit.v3" Version="3.2.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
        <PackageReference Include="Verify.XunitV3" Version="31.27.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
        <PackageReference Include="NSubstitute" Version="6.0.0" />
        <PackageReference Include="Shouldly" Version="4.3.0" />
        <PackageReference Include="PublicApiGenerator" Version="11.5.4" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\lib\Vertical.Cli.csproj" />
    </ItemGroup>
    
</Project>