// // <auto-generated/>
// #nullable enable
//
// namespace Vertical.Cli;
//
// file sealed class IModelImpl_<ClassId> : global::Vertical.Cli.SourceGenerator.Tests.IModel
// {
//    public required global::System.String String { get; init; }
//    public required global::System.Int32 Int { get; init; }
//    public required global::System.Int32? NullableInt { get; init; }
//    public required ConsoleKey Key { get; init; }
//    public required ConsoleKey? NullableKey { get; init; }
//    public required FileInfo File { get; init; }
//    public required DirectoryInfo Directory { get; init; }
//    public required Uri Link { get; init; }
//    public required global::System.String[] Array { get; init; }
//    public required global::System.Collections.Generic.List<global::System.String> List { get; init; }
//    public required global::System.Collections.Generic.LinkedList<global::System.String> LinkedList { get; init; }
//    public required global::System.Collections.Generic.HashSet<global::System.String> Set { get; init; }
//    public required global::System.Collections.Generic.SortedSet<global::System.String> SortedSet { get; init; }
//    public required global::System.Collections.Generic.IEnumerable<global::System.String> Enumerable { get; init; }
//    public required global::System.Collections.Generic.ICollection<global::System.String> Collection { get; init; }
//    public required global::System.Collections.Generic.IReadOnlyCollection<global::System.String> ReadOnlyCollection { get; init; }
//    public required global::System.Collections.Generic.IList<global::System.String> ListInterface { get; init; }
//    public required global::System.Collections.Generic.IReadOnlyList<global::System.String> ReadOnlyListInterface { get; init; }
//    public required global::System.Collections.Generic.ISet<global::System.String> SetInterface { get; init; }
//    public required global::System.Collections.Generic.IReadOnlySet<global::System.String> ReadOnlySetInterface { get; init; }
//    public required global::System.Collections.Immutable.ImmutableArray<global::System.String> ImmutableArray { get; init; }
//    public required global::System.Collections.Immutable.ImmutableList<global::System.String> ImmutableList { get; init; }
//    public required global::System.Collections.Immutable.ImmutableHashSet<global::System.String> ImmutableHashSet { get; init; }
//    public required global::System.Collections.Immutable.ImmutableSortedSet<global::System.String> ImmutableSortedSet { get; init; }
//    public required global::System.Collections.Immutable.ImmutableStack<global::System.String> ImmutableStack { get; init; }
//    public required global::System.Collections.Immutable.ImmutableQueue<global::System.String> ImmutableQueue { get; init; }
//    public required global::System.Collections.Generic.Stack<global::System.String> Stack { get; init; }
//    public required global::System.Collections.Generic.Queue<global::System.String> Queue { get; init; }
//
//    internal static global::Vertical.Cli.SourceGenerator.Tests.IModel Bind(global::Vertical.Cli.Binding.BindingContext<global::Vertical.Cli.SourceGenerator.Tests.IModel> context)
//    {
//       return new IModelImpl_<ClassId>
//       {
//          String = context.GetValue(x => x.String)
//          , Int = context.GetValue(x => x.Int)
//          , NullableInt = context.GetValue(x => x.NullableInt)
//          , Key = context.GetValue(x => x.Key)
//          , NullableKey = context.GetValue(x => x.NullableKey)
//          , File = context.GetValue(x => x.File)
//          , Directory = context.GetValue(x => x.Directory)
//          , Link = context.GetValue(x => x.Link)
//          , Array = context.GetValue(x => x.Array)
//          , List = context.GetValue(x => x.List)
//          , LinkedList = context.GetValue(x => x.LinkedList)
//          , Set = context.GetValue(x => x.Set)
//          , SortedSet = context.GetValue(x => x.SortedSet)
//          , Enumerable = context.GetValue(x => x.Enumerable)
//          , Collection = context.GetValue(x => x.Collection)
//          , ReadOnlyCollection = context.GetValue(x => x.ReadOnlyCollection)
//          , ListInterface = context.GetValue(x => x.ListInterface)
//          , ReadOnlyListInterface = context.GetValue(x => x.ReadOnlyListInterface)
//          , SetInterface = context.GetValue(x => x.SetInterface)
//          , ReadOnlySetInterface = context.GetValue(x => x.ReadOnlySetInterface)
//          , ImmutableArray = context.GetValue(x => x.ImmutableArray)
//          , ImmutableList = context.GetValue(x => x.ImmutableList)
//          , ImmutableHashSet = context.GetValue(x => x.ImmutableHashSet)
//          , ImmutableSortedSet = context.GetValue(x => x.ImmutableSortedSet)
//          , ImmutableStack = context.GetValue(x => x.ImmutableStack)
//          , ImmutableQueue = context.GetValue(x => x.ImmutableQueue)
//          , Stack = context.GetValue(x => x.Stack)
//          , Queue = context.GetValue(x => x.Queue)
//       };
//    }
// }
//
// file sealed class IParameterModelImpl_<ClassId> : global::Vertical.Cli.SourceGenerator.Tests.IParameterModel
// {
//    public required global::System.Boolean Switch { get; init; }
//
//    internal static global::Vertical.Cli.SourceGenerator.Tests.IParameterModel Bind(global::Vertical.Cli.Binding.BindingContext<global::Vertical.Cli.SourceGenerator.Tests.IParameterModel> context)
//    {
//       return new IParameterModelImpl_<ClassId>
//       {
//          Switch = context.GetValue(x => x.Switch)
//       };
//    }
// }
//
// /// <summary>
// /// Provides configuration extensions to the CommandLineApplication class.
// /// </summary>
// public static class CommandLineApplicationExtensions
// {
//    /// <summary>
//    /// Adds model binding configurations for types annotated with
//    /// <see cref="global::Vertical.Cli.Binding.GeneratedBindingAttribute"/>.
//    /// </summary>
//    /// <param name="app">The application instance to add configuration to.</param>
//    public static void Configure(this global::Vertical.Cli.CommandLineApplication app)
//    {
//       app.AddArgumentConverter(global::Vertical.Cli.Conversion.Converters.Default);
//       app.AddArgumentConverter(global::Vertical.Cli.Conversion.Converters.Parsable<global::System.Int32>());
//       app.AddArgumentConverter(global::Vertical.Cli.Conversion.Converters.NullParsable<global::System.Int32>());
//       app.AddCollectionConverter<global::System.String, global::System.String[]>(values => values.ToArray);
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Generic.List<global::System.String>>(values => values.ToList);
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Generic.HashSet<global::System.String>>(values => new global::System.Collections.Generic.HashSet(values));
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Generic.SortedSet<global::System.String>>(values => new global::System.Collections.Generic.SortedSet(values));
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Generic.IEnumerable<global::System.String>>(values => values.ToArray);
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Generic.ICollection<global::System.String>>(values => values.ToList);
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Generic.IReadOnlyCollection<global::System.String>>(values => values.ToArray);
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Generic.IList<global::System.String>>(values => values.ToList);
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Generic.IReadOnlyList<global::System.String>>(values => values.ToArray);
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Generic.ISet<global::System.String>>(values => new global::System.Collections.Generic.HashSet(values));
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Generic.IReadOnlySet<global::System.String>>(values => new global::System.Collections.Generic.HashSet(values));
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Immutable.ImmutableArray<global::System.String>>(values => [..values]);
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Immutable.ImmutableList<global::System.String>>(values => [..values]);
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Immutable.ImmutableHashSet<global::System.String>>(values => [..values]);
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Immutable.ImmutableSortedSet<global::System.String>>(values => [..values]);
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Immutable.ImmutableStack<global::System.String>>(values => [..values]);
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Immutable.ImmutableQueue<global::System.String>>(values => [..values]);
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Generic.Stack<global::System.String>>(values => new global::System.Collections.Generic.Stack(values));
//       app.AddCollectionConverter<global::System.String, global::System.Collections.Generic.Queue<global::System.String>>(values => new global::System.Collections.Generic.Queue(values));
//       app.AddArgumentConverter(global::Vertical.Cli.Conversion.Converters.Parsable<global::System.Boolean>());
//       app.ConfigureParser<global::Vertical.Cli.SourceGenerator.Tests.IModel>(builder => builder.SetBinder(IModelImpl_<ClassId>.Bind));
//       app.ConfigureParser<global::Vertical.Cli.SourceGenerator.Tests.IParameterModel>(builder => builder.SetBinder(IParameterModelImpl_<ClassId>.Bind));
//    }
//
//    /// <summary>
//    /// Calls the <c>Configure</c> and <c>RunAsync</c> methods.
//    /// </summary>
//    /// <param name="app">The application instance to add configuration to.</param>
//    /// <param name="args">Arguments provided by the application's entry point..</param>
//    /// <returns>A task that wraps the integer result code.</returns>
//    public static async global::System.Threading.Tasks.Task<int> ConfigureAndRunAsync(this global::Vertical.Cli.CommandLineApplication app, string[] args)
//    {
//       app.Configure();
//       return await app.RunAsync(args);
//    }
// }
