//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vertical.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vertical.Cli.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Threading.Tasks;
        /// 
        ///namespace Vertical.Cli
        ///{
        ///    namespace Configuration
        ///    {
        ///        public interface IRootCommandBuilder&lt;TModel, TResult&gt;
        ///        {
        ///        }
        ///    }
        ///    
        ///    public interface IRootCommand&lt;TModel, TResult&gt;
        ///    {
        ///    }
        ///
        ///    public static class RootCommand
        ///    {
        ///        public static IRootCommand&lt;TModel, TResult&gt; Create&lt;TModel, TResult&gt;(
        ///            string id,
        ///            Action&lt;Configuration.IRootCommandBuilder&lt;TModel, TResult&gt;&gt; configure) =&gt; nul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProgramCSharpCode {
            get {
                return ResourceManager.GetString("ProgramCSharpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Vertical.Cli;
        ///
        ///namespace TestSetup
        ///{    
        ///    public enum Compression { None, GZip }
        ///
        ///    public record FileCopyParameters(
        ///        FileInfo Source,
        ///        FileInfo Dest,
        ///        Compression Compression,
        ///        bool Overwrite);
        ///
        ///    public static class Program
        ///    {
        ///        public static Task&lt;int&gt; Main(string[] args)
        ///        {
        ///            _ = RootCommand.Create&lt;FileCopyParameters, Task&lt;int&gt;&gt;(
        ///                id: &quot;copy&quot;,
        ///                root =&gt; { });
        ///
        ///            ret [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProgramUnit {
            get {
                return ResourceManager.GetString("ProgramUnit", resourceCulture);
            }
        }
    }
}
