using System.Text;
using Microsoft.CodeAnalysis;

namespace Vertical.Cli.Analysis;

public class CodeGenerator
{
    public static string Generate(TypeModel[] typeModels)
    {
        var buffer = new StringBuilder(5000);
        var writer = new IndentedCodeWriter(buffer, 0);
        
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine($"namespace {NamingConvention.VerticalCliNs};");
        writer.WriteLine();

        WriteModelClasses(typeModels, ref writer);
        WriteExtensionClass(typeModels, ref writer);

        return buffer.ToString();
    }

    private static void WriteModelClasses(TypeModel[] typeModels, ref IndentedCodeWriter writer)
    {
        foreach (var typeModel in typeModels)
        {
            WriteModelClass(typeModel, ref writer);
            writer.WriteLine();
        }
    }

    private static void WriteModelClass(TypeModel typeModel, ref IndentedCodeWriter writer)
    {
        writer.WriteLine($"file sealed class {typeModel.GeneratedTypeName} : {typeModel.TypeSymbol.GlobalName}");
        writer.WriteBlock(
            IndentedCodeWriter.CurlyBraces,
            (ref inner) => WriteModelClassBody(typeModel, ref inner));
    }

    private static void WriteModelClassBody(TypeModel typeModel, ref IndentedCodeWriter writer)
    {
        foreach (var property in typeModel.PropertySymbols)
        {
            writer.WriteLine($"public required {property.Type.GlobalName} {property.Name} {{ get; init; }}");
        }

        if (typeModel.PropertySymbols.Length > 0) writer.WriteLine();

        var bindingContextType = string.Format(NamingConvention.BindingContextClass, typeModel.TypeSymbol.GlobalName);
        writer.WriteLine($"internal static {typeModel.TypeSymbol.GlobalName} Bind({bindingContextType} context)");
        writer.WriteBlock(
            IndentedCodeWriter.CurlyBraces,
            (ref body) =>
            {
                body.WriteLine($"return new {typeModel.GeneratedTypeName}");
                body.WriteInitializerList(
                    IndentedCodeWriter.CurlyBraces,
                    typeModel.PropertySymbols.Select(property => $"{property.Name} = context.GetValue(x => x.{property.Name})"),
                    returnToNewLine: false);
                body.WriteLine(";");
            });
    }

    private static void WriteExtensionClass(TypeModel[] typeModels, ref IndentedCodeWriter writer)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Provides configuration extensions to the CommandLineApplication class.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("public static class CommandLineApplicationExtensions");
        writer.WriteBlock(IndentedCodeWriter.CurlyBraces, (ref inner) => WriteExtensionClassBody(typeModels, ref inner));
    }

    private static void WriteExtensionClassBody(TypeModel[] typeModels, ref IndentedCodeWriter writer)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Adds model binding configurations for types annotated with");
        writer.WriteLine($"/// <see cref=\"global::{NamingConvention.VerticalCliBindingNs}.GeneratedBindingAttribute\"/>.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <param name=\"app\">The application instance to add configuration to.</param>");
        writer.WriteLine($"public static void Configure(this {NamingConvention.CommandLineApplicationClassFqName} app)");
        writer.WriteBlock(IndentedCodeWriter.CurlyBraces, (ref inner) => WriteConfigureMethodBody(typeModels, ref inner));
        writer.WriteLine();
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Calls the <c>Configure</c> and <c>RunAsync</c> methods.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("/// <param name=\"app\">The application instance to add configuration to.</param>");
        writer.WriteLine("/// <param name=\"args\">Arguments provided by the application's entry point..</param>");
        writer.WriteLine("/// <returns>A task that wraps the integer result code.</returns>");
        writer.WriteLine($"public static async global::System.Threading.Tasks.Task<int> ConfigureAndRunAsync(this {NamingConvention.CommandLineApplicationClassFqName} app, string[] args)");
        writer.WriteBlock(IndentedCodeWriter.CurlyBraces, (ref inner) =>
        {
            inner.WriteLine("app.Configure();");
            inner.WriteLine("return await app.RunAsync(args);");
        });
    }

    private static void WriteConfigureMethodBody(TypeModel[] typeModels, ref IndentedCodeWriter writer)
    {
        AddConverters(typeModels, ref writer);
        AddModelBinders(typeModels, ref writer);
    }

    private static void AddModelBinders(TypeModel[] typeModels, ref IndentedCodeWriter writer)
    {
        foreach (var typeModel in typeModels)
        {
            writer.WriteLine($"app.ConfigureParser<{typeModel.TypeSymbol.GlobalName}>(builder => builder.SetBinder({typeModel.GeneratedTypeName}.Bind));");
        }
    }

    private static void AddConverters(TypeModel[] typeModels, ref IndentedCodeWriter writer)
    {
        var propertyTypes = typeModels
            .SelectMany(model => model.PropertyTypes)
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<ITypeSymbol>();

        var visitedArgumentTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var type in propertyTypes)
        {
            if (ConversionExpressionFactory.TryCreate(type) is not { } expressionInfo)
                continue;

            switch (expressionInfo)
            {
                case ArgumentConversionCall argCall when visitedArgumentTypes.Add(argCall.TargetType):
                    writer.WriteLine($"app.AddArgumentConverter({argCall.ConverterExpression});");
                    break;
                
                case CollectionConversionCall collectionCall:
                    if (collectionCall.ArgumentConversionCall is not null && visitedArgumentTypes.Add(collectionCall.ElementType))
                    {
                        writer.WriteLine($"app.AddArgumentConverter({collectionCall.ArgumentConversionCall.ConverterExpression});");
                    }

                    var typeCsv = $"{collectionCall.ElementType.GlobalName}, {collectionCall.CollectionType.GlobalName}";
                    writer.WriteLine($"app.AddCollectionConverter<{typeCsv}>({collectionCall.CollectionCreationExpression});");
                    break;
            }
        }
    }
}