name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        dotnet-version: ['10.0.x']
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup .NET Code SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Run tests
        run: dotnet test --no-restore --collect:"XPlat Code Coverage"
      - name: Build source generator
        run: dotnet build src/generator/ -c Release --no-restore -o analyzers
      - name: Pack core libraries
        run: |
          dotnet pack src/lib -c Release --no-restore -p:ContinuousIntegrationBuild=true -o ./pack
          dotnet pack src/dep-injection -c Release --no-restore -p:ContinuousIntegrationBuil=true -o ./pack
      - name: Retain latest package build
        uses: actions/upload-artifact@v4
        with:
          name: latest-build
          path: ./pack/
          retention-days: 7
