name: Pre release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Code SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Set build label
        run: echo "DEVLABEL=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Build source generator
        run: dotnet build -c Release --no-restore -o lib src/Vertical.Cli.SourceGenerator/
      - name: Stage source generator assembly
        run: mkdir -p src/Vertical.Cli/bin/Release && cp lib/Vertical.Cli.SourceGenerator.dll src/Vertical.Cli/bin/Release
      - name: Build pre-release package
        run: dotnet pack src/Vertical.Cli -c Release --no-restore -p:VersionSuffix=dev.${{ env.DEVLABEL }}.${{ github.run_number }} -o ./pack
      #- name: Publish packages to NuGet
      #  run: dotnet nuget push ./pack/*[^.symbols].nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_ORG_PUSH_KEY }}